pipeline {
    agent any

    parameters {
        booleanParam(name: "confirmDeploy", description: "Are you sure you want to deploy it in?", defaultValue: false)
        string(name: "deployEnv", description: "Which environment to deploy in?", defaultValue: '')
        choice(name: "deployAz", description: "Which AZ to deploy to?", choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"])
    }

    stages {
        stage("Demo") {
            steps {
                echo "Boolean is set to: ${params.confirmDeploy} \n"
                echo "String is set to: ${params.deployEnv} \n"
                echo "Choice is set to: ${params.deployAz} \n"
            }
        }
    }
}