pipeline {
    agent any

    environment {
        def myString = "Hello World"
        def myNumber = 10
        def myBool = true
    }

    stages {
        stage("Demo") {
            steps {
                echo "myString is set to: ${myString}"
                echo "myNumber is set to: ${myNumber}"
                echo "myBool is set to: ${myBool}"
            }
        }
    }
}